<?php

$uri = Zend_Registry::get('uri');

if (!isset($noSubContentBreak) || !$noSubContentBreak) {
	//echo '<br>';
}
if (isset($headline) && !empty($headline)) {
	/*
		<h2 class="subcontentHeadline"><?php echo $headline; ?></h2>
 			-> color: #666699; font-size: 15px; font-weight: bold; margin-top: 5px; margin-bottom: 0; padding: 2px 10px;
 			-> <h2 style="color: #666699; font-size: 15px; font-weight: bold; margin: 0; padding: 0;">'.$headline.'</h2>
 	*/
	echo '<h2 style="color: #3b90ce; font-size: 15px; font-weight: bold; margin: 5px 0 0 10px; padding: 0;">'.$headline.'</h2>';
}
if (isset($headlineRight) && !empty($headlineRight)) {
	echo $headlineRight;
}
?>

<table style="width: 800px; border-collapse: separate !important; border-spacing: 0;" align="left" border="0" cellpadding="0" cellspacing="0">
<tr>
<td style="border: 1px solid #DBDBDC;">

<div style="padding: 6px 10px;">
<?php
	if (isset($htmlAlertHeadline) && !empty($htmlAlertHeadline)) {
		echo '
			<h2 style="margin: 0 0 10px 0; padding: 0; white-space: nowrap;">'.$htmlAlertHeadline.'</h2>
		';
	}
	echo $subcontent;
?>
<br>
<!-- <small>Thank you for using Fulcrum Construction Management&trade; Software</small> -->
<small>This email was generated by <a href="<?php echo $uri->http; ?>" style="text-decoration:none; color:#3b90ce; font-size:15px; font-weight: bold;">FULCRUM</a> Construction Management&trade; Software</small>
</div>
</td>
</tr>
</table>